[package]
name = "atomic-polyfill"
version = "0.1.2"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
description = "Atomic polyfills, for targets where they're not available."
repository = "https://github.com/akiles/atomic-polyfill"
edition = "2018"
readme = "README.md"
license = "MIT OR Apache-2.0"

categories = [
    "embedded",
    "no-std",
    "concurrency",
]

[dependencies]
cortex-m = "0.7.1"