[package]
name = "atomic-polyfill"
version = "0.1.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"

[features]
# If enabled, core-compatible atomics using critical sections are exported.
# If disabled, core::sync::atomic is reexported
polyfill = ["cortex-m"]

[dependencies]
cortex-m = { version = "0.7.1", optional = true }